- name: remove unused packets
  become: true
  apt:
    name: 
      - unattended-upgrades
      - snapd
      - modemmanager
    state: absent
    autoclean: true
    autoremove: true
    update_cache: true
  environment: "{{ proxy_env }}"

# - name: Forwarding
#   become: true
#   ansible.posix.sysctl:
#     name: net.ipv4.ip_forward
#     value: '1'
#     sysctl_set: true

- name: Swappiness
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '2'
    state: present

- name: Disable IPv6
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: true

- name: Disable IPv6 default
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: true

- name: Disable IPv6 default lo
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    sysctl_set: true