- name: Загрузка CNI плагинов
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-{{ (ansible_architecture == 'aarch64') | ternary('arm64', 'amd64') }}-v1.0.0.tgz"
    dest: "/tmp/cni-plugins.tgz"
  environment: "{{ proxy_env }}"

- name: Создание директории /opt/cni/bin
  file:
    path: "/opt/cni/bin"
    state: directory

- name: Распаковка CNI плагинов
  unarchive:
    src: "/tmp/cni-plugins.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes

- name: Разрешение маршрутизации контейнерного трафика через bridge сеть
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  when: ansible_facts['os_family']|lower == 'debian' or ansible_facts['os_family']|lower == 'redhat'

- name: Создание файла /etc/sysctl.d/bridge.conf для сохранения настроек
  copy:
    dest: "/etc/sysctl.d/bridge.conf"
    content: |
      net.bridge.bridge-nf-call-arptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
